server:
  port: 8083
  
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/alejorcode/microservices-tuto
          search-paths: config-data
          clone-on-start: true
          
          
